name: bilibili
description: A bilibli video gui downloader.
publish_to: 'none'

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: 1.0.4
  device_preview: 1.0.0
  dio: 4.0.4
  ffmpeg_kit_flutter_min: 4.5.1
  flutter_easyloading: 3.0.3
  gallery_saver: 2.3.2
  get: 4.6.1
  oktoast: 3.1.5
  path: 1.8.0
  path_provider: 2.0.9
  permission_handler: 8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: 2.0.5
  flutter_launcher_icons: 0.9.2

flutter:
  uses-material-design: true

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/icons/preset/logo.png'
  fullscreen: true

flutter_icons:
  image_path: 'assets/icons/preset/logo.png'
  android: true
  ios: true
  remove_alpha_ios: true
